import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const accounts = sqliteTable("accounts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  shortName: text("short_name").notNull(),
  positioning: text("positioning").notNull(),
  color: text("color").notNull(),
  weeklyTarget: integer("weekly_target").notNull().default(4),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const contentItems = sqliteTable("content_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  accountId: integer("account_id").notNull(),
  title: text("title").notNull(),
  topic: text("topic").notNull().default(""),
  stage: text("stage").notNull().default("idea"),
  hook: text("hook").notNull().default(""),
  script: text("script").notNull().default(""),
  shotNotes: text("shot_notes").notNull().default(""),
  publishCopy: text("publish_copy").notNull().default(""),
  publishDate: text("publish_date").notNull().default(""),
  owner: text("owner").notNull().default("我"),
  priority: text("priority").notNull().default("normal"),
  views: integer("views").notNull().default(0),
  likes: integer("likes").notNull().default(0),
  comments: integer("comments").notNull().default(0),
  shares: integer("shares").notNull().default(0),
  follows: integer("follows").notNull().default(0),
  review: text("review").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  sourceUrl: text("source_url").notNull().default(""),
  sourceScript: text("source_script").notNull().default(""),
  structureTemplate: text("structure_template").notNull().default(""),
  adaptationNotes: text("adaptation_notes").notNull().default(""),
  estimatedMinutes: integer("estimated_minutes").notNull().default(2),
  imageCount: integer("image_count").notNull().default(4),
  visualPlan: text("visual_plan").notNull().default(""),
  openingAnimation: text("opening_animation").notNull().default(""),
  voiceProfile: text("voice_profile").notNull().default("历史讲解固定音色"),
  voiceStatus: text("voice_status").notNull().default("not_configured"),
  voiceReferenceUrl: text("voice_reference_url").notNull().default(""),
  audioUrl: text("audio_url").notNull().default(""),
  editTool: text("edit_tool").notNull().default("待确认"),
  editPlan: text("edit_plan").notNull().default(""),
  metricsScreenshotUrl: text("metrics_screenshot_url").notNull().default(""),
  workflowProfile: text("workflow_profile").notNull().default("history-v3.11.0"),
  intakeMode: text("intake_mode").notNull().default("video_link"),
  runMode: text("run_mode").notNull().default("derivative"),
  bookTitle: text("book_title").notNull().default(""),
  bookAuthor: text("book_author").notNull().default(""),
  evidenceStatus: text("evidence_status").notNull().default("pending"),
  evidenceNotes: text("evidence_notes").notNull().default(""),
  originalityStatus: text("originality_status").notNull().default("pending"),
  originalitySimilarity: text("originality_similarity").notNull().default(""),
  scriptApproval: text("script_approval").notNull().default("pending"),
  complianceStatus: text("compliance_status").notNull().default("pending"),
  titlesStatus: text("titles_status").notNull().default("pending"),
  titleCandidates: text("title_candidates").notNull().default(""),
  selectedLongTitle: text("selected_long_title").notNull().default(""),
  selectedShortTitle: text("selected_short_title").notNull().default(""),
  selectedTopics: text("selected_topics").notNull().default(""),
  styleSampleStatus: text("style_sample_status").notNull().default("pending"),
  imagesApproval: text("images_approval").notNull().default("pending"),
  deliveryStatus: text("delivery_status").notNull().default("pending"),
  publicationStatus: text("publication_status").notNull().default("locked"),
  analyticsHorizon: text("analytics_horizon").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("idx_content_items_account_stage").on(table.accountId, table.stage),
  index("idx_content_items_updated_at").on(table.updatedAt),
]);
